services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blogs
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
